name: Bug
description: File a bug/issue
title: "[Bug] Your issue here"
labels: [bug, unconfirmed]
body:
- type: markdown
  attributes:
    value: |
      Hi! Thanks for coming to report a bug in the MuffinHunt Datapack! Please make sure that this is a bug with this datapack, and not another one! Fill out this form, and the bug will be reported!
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the issue you encountered!
    options:
    - label: I have searched the existing issues and did not find an existing one
      required: true
- type: textarea
  attributes:
    label: Actual Behavior
    description: A description of the issue you've encountered.
    placeholder: It didn't work...
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A description of what you expected to happen.
    placeholder: It should have worked...
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Datapack**: v1.7.1
        - **Minecraft**: 1.19
    value: |
        - OS:
        - Datapack:
        - Minecraft:
    render: Markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    placeholder: Anything else here...
  validations:
    required: false