name: Feature request
description: Suggest a feature!
title: "[Feature Request] Your request here!"
body:
- type: markdown
  attributes:
    value: |
      Hi! Thanks for coming to suggest a feature for the MuffinHunt Datapack! Please make sure that you've considered this feature for a while. If you aren't sure, bring it up in the [discussions](https://github.com/osfanbuff63/muffinhunt-datapack/) first!
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the issue you encountered!
    options:
    - label: I have searched the existing issues and did not find an existing one
      required: true
- type: textarea
  attributes:
    label: What's your feature idea?
    description: A short description of your idea
    placeholder: I wish this existed...
  validations:
    required: true
- type: textarea
  attributes:
    label: How should it work?
    description: A description of how you think your idea could work
    placeholder: Maybe if you clicked a dancing allay...
  validations:
    required: true    
- type: textarea
  attributes:
    label: Anything else?
    description: Any other things related to this feature request?
    placeholder: Any thoughts?
  validations:
    required: false
        