name: Approve pull request
on: workflow_dispatch
jobs:
  approve-pr:
    runs-on: ubuntu-latest
    steps:
      
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 78
    
     
