name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Check commands
        uses: mcbeet/check-commands@v1
        with:
          source: .
      - name: Check JSON
        uses: ocular-d/json-lint@0.0.2
   
  build-packsquash:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@master
        with:
          path: ./
          token: ${{ secrets.GITHUB_TOKEN }}
          minify_json_files: true
          validate_pack_metadata_file: true
          allow_optifine_mod: true
          delete_bloat_json_keys: true
  
