# Notice how there is an extra complile and upload step.
# This is due to how the build-main job checks for errors. Instead of using a script,
# such as, /gradlew build, with this being a datapack, it checks the source files instead. (see Check commands and Check JSON.)
# This is completely intentional, please do not create a PR changing it!

name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Check commands
        uses: mcbeet/check-commands@v1.0.6
        with:
          source: .
          minecraft: 1.18
      - name: Check JSON
        uses: ocular-d/json-linter@0.0.2
   
  build-packsquash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@master
        with:
          path: ./
          token: ${{ secrets.GITHUB_TOKEN }}
          minify_json_files: true
          validate_pack_metadata_file: true
          allow_optifine_mod: true
          delete_bloat_json_keys: true
  
