name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # I know, this is useless, but see git log xD
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Check commands
        uses: mcbeet/check-commands@v1.0.6
        with:
          source: .
          minecraft: 1.18
      - name: Check JSON
        uses: ocular-d/json-linter@0.0.2
   
  build-packsquash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@master
        with:
          path: ./
          token: ${{ secrets.GITHUB_TOKEN }}
          minify_json_files: true
          validate_pack_metadata_file: true
          allow_optifine_mod: true
          delete_bloat_json_keys: true
  
