
name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test-datapack-mac-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest,ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Zip files
        uses: vimtor/action-zip@v1
        with:
          files: ./
          dest: muffinhunt-datapack.zip
      - name: Setup Minecraft
        uses: mcenv/setup-minecraft@v1
        with:
          version: "1.18.2"
      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Run Minecraft
        run: |
              java -jar minecraft/server.jar 
              sleep 100
              cd minecraft
              stop
      - name: Move files to server folder
        run: |
             cd ..
             mv muffinhunt-datapack.zip minecraft/world/datapacks/
      - name: Start server
        run: |
              java -jar minecraft/server.jar
              sleep 100
              cd minecraft
              stop
              
  test-datapack-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Zip files
        uses: vimtor/action-zip@v1
        with:
          files: ./
          dest: muffinhunt-datapack.zip
      - name: Setup Minecraft
        uses: mcenv/setup-minecraft@v1
        with:
          version: "1.18.2"
      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Run Minecraft
        run: |
              java -jar minecraft/server.jar 
              timeout /t 100
              cd minecraft
              stop
      - name: Move files to server folder
        run: |
             cd ..
             move muffinhunt-datapack.zip minecraft/world/datapacks/
      - name: Start server
        run: |
              java -jar minecraft/server.jar
              timeout /t 100
              cd minecraft
              stop

      
      

      
      
      
