name: Build and deploy Jekyll site to GitHub Pages
on:
  push:
    branches: [master]
    paths:
      - docs/**
  pull_request:
    branches: [master]
    paths: 
     - docs/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event_name !== 'pull_request' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build and deploy
        uses: helaili/jekyll-action@2.0.5    
        with:                                
          token: ${{ secrets.GITHUB_TOKEN }}
          pre_build_commands: cd docs
  deploy-pr:
    runs-on: ubuntu-latest
    environment: development
    if: ${{ github.event_name !== 'pull_request' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build and deploy
        uses: helaili/jekyll-action@2.0.5    
        with:                                
          token: ${{ secrets.GITHUB_TOKEN }}
          pre_build_commands: cd docs