name: Markdown Lint
on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run Markdown Lint
        uses: articulate/actions-markdownlint@v1
