name: Optimize datapack
on: [push, pull_request]
jobs:
   packsquash:
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repo
       uses: actions/checkout@v2
     - name: Setup Node.js  
       uses: actions/setup-node@v3.0.0
       with:
         node-version: '>=16.14.0'
     - name: Clone repository
       uses: actions/checkout@v2
       with:
          fetch-depth: 0
     - name: Run PackSquash
       uses: ComunidadAylas/PackSquash-action@v2
       with:
          path: ./
          repo_token: ${{ secrets.packsquash_token }}
          
