name: Optimize datapack
on: [push, pull_request]
jobs:
   packsquash:
    name: Optimize datapack
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repo
       uses: actions/checkout@v2
     - name: Setup Node.js  
       uses: actions/setup-node@v3.0.0
       with:
         node-version: '>=16.14.0'
     - name: Clone repository
       uses: actions/checkout@v2
       with:
          fetch-depth: 0
     - name: Run PackSquash
       uses: ComunidadAylas/PackSquash-action@v2
       with:
          path: ./
          token: ${{ secrets.packsquash_token }}
          minify_json_files: true
          validate_pack_metadata_file: true
          allow_optifine_mod: true
          delete_bloat_json_keys: true
          
          
