name: Optimize datapack pack
on: [push, pull_request]
jobs:
   packsquash:
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
     - name: Install 
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
         node-version: '17'
     - run: npm install
     - run: npm test
     - name: Clone repository
       uses: actions/checkout@v2
       with:
          fetch-depth: 0
     - name: Run PackSquash
       uses: ComunidadAylas/PackSquash-action@v2
       with:
          path: ./
          repo_token: ${{ secrets.packsquash_token }}
          
