name: Optimize datapack
on: [push, pull_request]
jobs:
   packsquash:
    name: Optimize datapack
    runs-on: ubuntu-latest
    steps:
     - name: Clone repository
       uses: actions/checkout@v3
       with:
          fetch-depth: 0
     - name: Run PackSquash
       uses: ComunidadAylas/PackSquash-action@e12b951df62760df07b6d7d2fe386cdaafd52272
       with:
          path: ./
          token: ${{ secrets.packsquash_token }}
          minify_json_files: true
          validate_pack_metadata_file: true
          allow_optifine_mod: true
          delete_bloat_json_keys: true
