name: Upload optimized datapack
on: 
  push:
    tags:
    - 'v*'
  workflow_dispatch:
jobs:
   packsquash:
    name: Optimize datapack
    runs-on: ubuntu-latest
    steps:
     - name: Clone repository
       uses: actions/checkout@v3
       with:
          fetch-depth: 0
     - name: Run PackSquash
       uses: ComunidadAylas/PackSquash-action@master
       with:
          path: ./
          token: ${{ secrets.GITHUB_TOKEN }}
          minify_json_files: true
          validate_pack_metadata_file: true
          allow_optifine_mod: true
          delete_bloat_json_keys: true
          artifact_name: 'optimized-muffinhunt-datapack.zip'
     - name: Download optimized pack
       uses: actions/download-artifact@v3
       with:
        name: optimized-muffinhunt-datapack.zip
        path: ./
     - name: Publish optimized datapack
       uses: svenstaro/upload-release-action@v2
       with: 
         repo_token: ${{ secrets.GITHUB_TOKEN }}
         tag: ${{ github.ref }}
         file: './optimized-muffinhunt-datapack.zip'
