name: Publish
on:
 workflow_dispatch:
jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'muffinhunt-datapack.zip'
        directory: './'
        path: './'
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
         name: muffinhunt-datapack.zip
         path: ./
