name: Publish
on:
 release:
  published:


jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'muffinhunt-datapack.zip'
        exclusions: '*.git* /docs/*.md'
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.zip_files }}
        file: target/release/muffinhunt-datapack
        asset_name: muffinhunt-datapack
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
