name: Publish
on:
 workflow_dispatch:
 push:
 pull_request:
jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'muffinhunt-datapack.zip'
        directory: './'
        path: './'
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
         name: muffinhunt-datapack.zip
         path: ./
    - name: Create release
      uses: ncipollo/release-action@1.9.0
      with:
        artifacts: "muffinhunt-datapack.zip"
        prerelease: true
        tag: muffinhunt-dev-build
        commit: master
        token: ${{ secrets.GITHUB_TOKEN }}
